[[redirects]]
  from = "http://videos.hydro-physics.co/:videoId"
  to = "https://videos.sewercam.net/:videoId"
  status = 301
  force = true

[[redirects]]
  from = "https://videos.hydro-physics.co/:videoId"
  to = "https://videos.sewercam.net/:videoId"
  status = 301
  force = true