[[redirects]]
  from = "http://videos.hydro-physics.co/*"
  to = "https://videos.sewercam.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://videos.hydro-physics.co/*"
  to = "https://videos.sewercam.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://www.sewercam.net/?from-hydro-physics=true"
  status = 301
  force = true